language: ruby

rvm:
  - 2.2

before_script:
  - gem install awesome_bot
  - gem install mdl

script:
- awesome_bot README.md --allow-dupe --white-list www.probetech.co.uk,people.zeelandnet.nl,gabby.8m.com,web.media.mit.edu,nutterscreatures.weebly.com,meliweb.net,creaturescommunity.net,www.ettin-trix.be,creatures.virtualheaven.nl,www.reocities.com,cglaboratory.org,www.generation5.org,thenorndatingagency.webs.com,www.norns.webs.com,jodiescreaturebreeds.webs.com,creaturesdev.webs.com,grendelwoods.webs.com,aithaluna.webs.com,albia.nuclearrainbow.com,icepenguin.ifastnet.com,creatures-online.co.uk,www.prosiebengames.de,web.archive.org,creaturesconnection.sourceforge.io,www.kridre.de,www.happy-creatures.de.vu,www.edash.screaming.net,geatville.zzl.org,m.fanfiction.net,www.freewebs.com,nirax.webs.com,nornity.blogspot.com,home.arcor.de # Allow duplicate links
- mdl --rules ~MD013,~MD033 README.md # Ignore line length (MD013) and inline HTML (MD033) Rules
